{% set name = "minian" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  # Uncomment the following line if the package is pure Python and the recipe
  # is exactly the same for all platforms. It is okay if the dependencies are
  # not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python
  # for more details.
  # noarch: python

  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

  # If the installation is complex, or different between Unix and Windows,
  # use separate bld.bat and build.sh files instead of this key. By default,
  # the package will be built for the Python versions supported by conda-forge
  # and for all major OSs. Add the line "skip: True  # [py<35]" (for example)
  # to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit
  # to Windows.
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required
    # compilers as separate entries here. Compilers are named 'c', 'cxx' and 'fortran'.
    #- {{ compiler('c') }}
  host:
    - pip
    - av=7.0.1
    - bokeh=1.4.0
    - bottleneck=1.3.2
    - cairo=1.16.0
    - cvxpy=1.0.27
    - dask=2.11.0
    - datashader=0.10.0
    - distributed=2.11.0
    - ecos=2.0.7
    - ffmpeg=4.1.3
    - fftw=3.3.8
    - holoviews=1.12.7
    - ipython=7.12.0
    - ipywidgets=7.5.1
    - jupyter=1.0.0
    - matplotlib=3.1.3
    - natsort=7.0.1
    - netcdf4=1.5.3
    - networkx=2.4
    - nodejs=13.9.0
    - numba=0.48.0
    - numpy=1.18.1
    - opencv=4.2.0
    - pandas=1.0.1
    - panel=0.8.0
    - papermill=2.0.0
    - param=1.9.3
    - pip=20.0.2
    - pyfftw=0.12.0
    - pytest-cov==2.9.0
    - python=3.8.1
    - scikit-image=0.16.2
    - scikit-learn=0.22.1
    - scipy=1.4.1
    - scs=2.1.1.2
    - statsmodels=0.11.1
    - tifffile=2020.2.16
    - tqdm=4.43.0
    - xarray=0.15.0
    - zarr=2.4.0

  run:
    - av=7.0.1
    - bokeh=1.4.0
    - bottleneck=1.3.2
    - cairo=1.16.0
    - cvxpy=1.0.27
    - dask=2.11.0
    - datashader=0.10.0
    - distributed=2.11.0
    - ecos=2.0.7
    - ffmpeg=4.1.3
    - fftw=3.3.8
    - holoviews=1.12.7
    - ipython=7.12.0
    - ipywidgets=7.5.1
    - jupyter=1.0.0
    - matplotlib=3.1.3
    - natsort=7.0.1
    - netcdf4=1.5.3
    - networkx=2.4
    - nodejs=13.9.0
    - numba=0.48.0
    - numpy=1.18.1
    - opencv=4.2.0
    - pandas=1.0.1
    - panel=0.8.0
    - papermill=2.0.0
    - param=1.9.3
    - pip=20.0.2
    - pyfftw=0.12.0
    - pytest-cov==2.9.0
    - python=3.8.1
    - scikit-image=0.16.2
    - scikit-learn=0.22.1
    - scipy=1.4.1
    - scs=2.1.1.2
    - statsmodels=0.11.1
    - tifffile=2020.2.16
    - tqdm=4.43.0
    - xarray=0.15.0
    - zarr=2.4.0


# Uncomment and fill in myproj metadata
#about:
#  home: https://github.com/conda-forge/conda-smithy
#  license: BSD-3-Clause
#  license_family: BSD
#  license_file: LICENSE

# Uncomment the following if this will be on a forge
# Remove these lines if this is only be used for CI
#extra:
#  recipe-maintainers:
#    - BobaFett
#    - LisaSimpson
