name: minian
channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - bokeh
  - bottleneck
  - cairo
  - cvxpy
  - dask=1
  - datashader
  - distributed
  - ecos
  - ffmpeg
  - fftw
  - holoviews
  - ipython
  - ipywidgets
  - jupyter
  - matplotlib
  - natsort
  - netcdf4
  - networkx
  - nodejs
  - numba
  - numpy
  - opencv
  - pandas
  - panel
  - papermill
  - param
  - pip
  - pyfftw
  - python
  - scikit-learn
  - scipy
  - scs
  - statsmodels
  - tifffile
  - tqdm
  - xarray
  - zarr
  - pip:
    - medpy
    - sk-video
    - ffmpeg-python
