name: minian
channels:
  # - cvxgrp
  # - ostrokach-forge
  # - numba
  # - pkgw-forge
  - conda-forge
  - defaults
dependencies:
  # - ansiwrap=0.8.3
  # - asciitree=0.3.3
  # - asn1crypto=0.24.0
  # - atk=2.25.90
  # - attrs=18.2.0
  - av
  # - backcall=0.1.0
  # - blas=1.1
  # - bleach=3.0.2
  - bokeh
  # - boost=1.64.0
  # - boost-cpp=1.64.0
  # - boto3=1.9.73
  # - botocore=1.12.74
  - bottleneck
  # - bzip2=1.0.6
  # - ca-certificates=2018.11.29
  - cairo
  # - cairomm=1.12.2
  # - certifi=2018.11.29
  # - cffi=1.11.5
  # - cftime=1.0.3.4
  # - cgal=4.11
  # - chardet=3.0.4
  # - click=7.0
  # - cloudpickle=0.6.1
  # - colorcet=1.0.0
  # - cryptography=2.2.1
  # - cryptography-vectors=2.4.2
  # - curl=7.63.0
  # - cvxopt=1.2.1
  - cvxpy
  # - cycler=0.10.0
  # - cytoolz=0.9.0.1
  - dask=1
  # - dask-core=1.0.0
  # - dask-image=0.2.0
  - datashader
  # - datashape=0.5.4
  # - dbus=1.13.0
  # - decorator=4.3.0
  # - dill=0.2.8.2
  - distributed
  # - docutils=0.14
  # - dsdp=5.8
  - ecos
  # - entrypoints=0.2.3
  # - expat=2.2.5
  # - fastcache=1.0.2
  # - fasteners=0.14.1
  - ffmpeg
  - fftw
  # - fontconfig=2.13.0
  # - freetype=2.8.1
  # - future=0.17.1
  # - gdk-pixbuf=2.36.12
  # - gettext=0.19.8.1
  # - giflib=5.1.4
  # - glib=2.55.0
  # - glpk=4.65
  # - gmp=6.1.2
  # - gnutls=3.5.19
  # - gobject-introspection=1.55.0
  # - graphite2=1.3.13
  # - graphviz=2.38.0
  # - gsl=2.2.1
  # - gst-plugins-base=1.12.5
  # - gstreamer=1.12.5
  # - h5netcdf=0.6.2
  # - h5py=2.8.0
  # - harfbuzz=1.8.5
  # - hdf4=4.2.13
  # - hdf5=1.10.2
  # - heapdict=1.0.0
  - holoviews
  # - icu=58.2
  # - idna=2.8
  # - imageio=2.4.1
  # - ipykernel=5.1.0
  - ipython
  # - ipython_genutils=0.2.0
  - ipywidgets
  # - jasper=1.900.1
  # - jedi=0.13.2
  # - jinja2=2.10
  # - jmespath=0.9.3
  # - jpeg=9c
  # - jsonschema=3.0.0a3
  - jupyter
  # - jupyter_client=5.2.4
  # - jupyter_console=6.0.0
  # - jupyter_core=4.4.0
  # - kiwisolver=1.0.1
  # - krb5=1.16.2
  # - lapack=3.6.1
  # - libcroco=0.6.12
  # - libcurl=7.63.0
  # - libedit=3.1.20170329
  # - libffi=3.2.1
  # - libgcc=7.2.0
  # - libgfortran=3.0.0
  # - libgfortran-ng=7.2.0
  # - libiconv=1.15
  # - libnetcdf=4.6.1
  # - libpng=1.6.34
  # - libprotobuf=3.5.2
  # - librsvg=2.40.19
  # - libsigcpp=2.10.0
  # - libsodium=1.0.16
  # - libssh2=1.8.0
  # - libtiff=4.0.9
  # - libtool=2.4.6
  # - libuuid=2.32.1
  # - libwebp=0.5.2
  # - libxcb=1.13
  # - libxml2=2.9.8
  # - llvmlite=0.26.0
  # - locket=0.2.0
  # - markdown=2.6.11
  # - markupsafe=1.1.0
  - matplotlib
  # - metis=5.1.0
  # - mistune=0.8.4
  # - mkl_fft=1.0.10
  # - mkl_random=1.0.2
  # - monotonic=1.5
  # - mpfr=3.1.5
  # - msgpack-python=0.6.0
  # - multipledispatch=0.6.0
  # - multiprocess=0.70.6.1
  - natsort
  # - nbconvert=5.3.1
  # - nbformat=4.4.0
  # - ncurses=6.1
  - netcdf4
  # - nettle=3.3
  - networkx
  - nodejs
  # - notebook=5.7.4
  - numba
  # - numcodecs=0.6.2
  - numpy
  # - olefile=0.46
  # - openblas=0.2.20
  - opencv
  # - openh264=1.7.0
  # - openssl=1.0.2p
  # - osqp=0.4.1
  # - packaging=18.0
  - pandas
  # - pandoc=2.5
  # - pandocfilters=1.4.2
  - panel
  # - pango=1.40.14
  - papermill
  - param
  # - paramnb=2.0.4
  # - parso=0.3.1
  # - partd=0.3.9
  # - patsy=0.5.1
  # - pcre=8.41
  # - pexpect=4.6.0
  # - phantomjs=2.1.1
  # - pickleshare=0.7.5
  # - pillow=5.2.0
  # - pims=0.4.1
  - pip
  # - pixman=0.34.0
  # - prometheus_client=0.5.0
  # - prompt_toolkit=2.0.7
  # - psutil=5.4.8
  # - pthread-stubs=0.4
  # - ptyprocess=0.6.0
  # - pycairo=1.13.3
  # - pycparser=2.19
  # - pyct=0.4.6
  # - pyct-core=0.4.6
  - pyfftw
  # - pygments=2.3.1
  # - pygobject=3.28.2
  # - pyopenssl=18.0.0
  # - pyparsing=2.3.0
  # - pyqt=5.6.0
  # - pyrsistent=0.14.8
  # - pysocks=1.6.8
  - python
  # - python-dateutil=2.7.5
  # - python-graphviz=0.8.4
  # - pytz=2018.7
  # - pyviz_comms=0.7.0
  # - pywavelets=1.0.1
  # - pyyaml=3.13
  # - pyzmq=17.1.2
  # - qt=5.6.2
  # - qtconsole=4.4.3
  # - readline=7.0
  # - requests=2.21.0
  # - s3transfer=0.1.13
  # - scikit-image=0.14.1
  - scikit-learn
  - scipy
  - scs
  # - seaborn=0.9.0
  # - selenium=3.141.0
  # - send2trash=1.5.0
  # - setuptools=40.6.3
  # - sip=4.18.1
  # - six=1.12.0
  # - slicerator=0.9.8
  # - sortedcontainers=2.1.0
  # - sparsehash=2.0.3
  # - sqlite=3.26.0
  - statsmodels
  # - suitesparse=4.5.6
  # - tbb=2018_20171205
  # - tblib=1.3.2
  # - terminado=0.8.1
  # - testpath=0.3.1
  # - textwrap3=0.9.1
  - tifffile
  # - tk=8.6.9
  # - toolz=0.9.0
  # - tornado=5.1.1
  - tqdm
  # - traitlets=4.3.2
  # - urllib3=1.24.1
  # - wcwidth=0.1.7
  # - webencodings=0.5.1
  # - wheel=0.32.3
  # - widgetsnbextension=3.4.2
  # - x264=1!152.20180717
  - xarray
  # - xorg-fixesproto=5.0
  # - xorg-inputproto=2.3.2
  # - xorg-kbproto=1.0.7
  # - xorg-libice=1.0.9
  # - xorg-libsm=1.2.3
  # - xorg-libx11=1.6.6
  # - xorg-libxau=1.0.8
  # - xorg-libxdmcp=1.1.2
  # - xorg-libxext=1.3.3
  # - xorg-libxfixes=5.0.3
  # - xorg-libxi=1.7.9
  # - xorg-libxrender=0.9.10
  # - xorg-libxtst=1.2.3
  # - xorg-recordproto=1.14.2
  # - xorg-renderproto=0.11.1
  # - xorg-xextproto=7.3.0
  # - xorg-xproto=7.0.31
  # - xz=5.2.4
  # - yaml=0.1.7
  - zarr
  # - zeromq=4.2.5
  # - zict=0.1.3
  # - zlib=1.2.11
  # - cvxcanon=0.1.1
  # - intel-openmp=2019.1
  # - libboost=1.65.1
  # - libgcc-ng=8.2.0
  # - libopenblas=0.3.3
  # - libopencv=3.4.1
  # - libstdcxx-ng=8.2.0
  # - mkl=2018.0.3
  # - numpy-base=1.15.4
  # - py-opencv=3.4.1
  # - cudatoolkit=9.0
  # - graph-tool=2.26
  # - at-spi2-atk=2.26.2
  # - at-spi2-core=2.28.0
  # - epoxy=1.5.2
  # - gtk3=3.22.30
  - pip:
    # - alabaster==0.7.12
    # - babel==2.6.0
    # - beautifulsoup4==4.6.3
    # - bs4==0.0.1
    # - colorlover==0.2.1
    # - cufflinks==0.14.6
    # - cython==0.29.2
    # - faker==1.0.1
    # - finance-enums==0.1.0
    # - imagesize==1.1.0
    # - ipysheet==0.2.0
    # - jupyterlab==0.35.4
    # - jupyterlab-server==0.2.0
    # - lineup-widget==1.0.7
    - medpy
    # - mimesis==3.0.0
    # - mock==2.0.0
    # - msgpack==0.6.0
    # - nibabel==2.3.1
    # - nose==1.3.7
    # - pbr==5.1.1
    # - perspective-python==0.1.3
    # - plotly==3.4.2
    # - pydicom==1.2.1
    # - pylantern==0.1.2
    # - qgrid==1.1.1
    # - retrying==1.3.3
    # - sidecar==0.2.0
    - sk-video
    # - sklearn==0.0
    # - snowballstemmer==1.2.1
    # - socketio-client-nexus==0.7.6
    # - sphinx==1.8.2
    # - sphinxcontrib-websupport==1.1.0
    # - text-unidecode==1.2
    # - ujson==1.35
    # - websocket-client==0.54.0
    # - websockets==7.0
    - ffmpeg-python
